language: erlang
otp_release:
   - 17.1
before_install:
   - git clone --branch v1.0.1 https://github.com/elixir-lang/elixir
   - make -C elixir
before_script:
  - "export PATH=`pwd`/elixir/bin:$PATH"
  - mix local.hex
  - mix deps.get
script: mix test
